name: Clean old Vercel deployments

on:
  push:
    branches:
      - main  # only run when pushing to main branch

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Delete old deployments (keep latest)
        run: |
          npx vercel rm misterymessage --safe --yes --token=${{ secrets.VERCEL_TOKEN }}
